workspace:
  base: /test
  path: drupal-core-require-dev

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
    - DOCUMENT_ROOT=/test/drupal-core-require-dev

pipeline:
  # Install all dependencies
  composer-install:
    group: prepare
    image: fpfis/httpd-php-dev:7.1
    environment:
      - COMPOSER_CACHE_DIR=/cache/composer
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress

  # Update by lowest dependencies
  composer-update-lowest:
    group: prepare-update
    image: fpfis/httpd-php-dev:7.1
    environment:
      - COMPOSER_CACHE_DIR=/cache/composer
    volumes:
    - /cache:/cache
    commands:
    - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

matrix:
  COMPOSER_BOUNDARY:
  - lowest
  - highest
