workspace:
  base: /test
  path: drupal-core-require-dev

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    environment:
      - DOCUMENT_ROOT=/test/drupal-core-require-dev

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: prepare-update
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.2-ci
    - 7.3-ci
