workspace:
  base: /test
  path: drupal-core-require-dev

services:
  web:
    image: fpfis/php71-dev
    environment:
      - DOCUMENT_ROOT=/test/drupal-core-require-dev

pipeline:
  # Install dependencies.
  composer-install:
    group: prepare
    image: fpfis/php71-dev
    commands:
      - composer install --ansi --no-suggest --no-progress
    volumes:
      - /cache:/cache

  # Update dependencies with --prefer-lowest.
  composer-update-lowest:
    group: prepare-update
    image: fpfis/php71-dev
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    volumes:
      - /cache:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  # Check vulnerable packages @Sensiolabs.
  test-composer-deps:
    group: check-prepare
    image: phpdrone/composer-sa-checker
    lock_file: composer.lock

matrix:
  COMPOSER_BOUNDARY:
    - highest
    - lowest
